# Generated by Django 4.1.5 on 2023-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recipe_url',
            field=models.URLField(blank=True),
        ),
    ]
