# Generated by Django 4.1.5 on 2023-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_menuitem_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
